### ISSUE TITLE
TwoDimPackingClass.solveで製品の座標が重なって出力される

### ISSUE THREAD

**Issue by rtonoue** [SaitoTsutomu/ortoolpy#1]
間違ったplatesのインデクスを参照してしまうため、アイテムを配置する座標がずれてしまいます。
l1003~1004
```
tmp.append((k, w, h) + plates[i][2:])
plates[i : i + 1] = [p for p in mnr[1:3] if p[0] * p[1] > 0]
```
修正案
```
tmp.append((k, w, h) + plates[mni][2:])
plates[mni : mni + 1] = [p for p in mnr[1:3] if p[0] * p[1] > 0]
```
最も余白が小さくなるplatesのインデックスmniを採用したいので、iではなくmniになります。

**Comment by SaitoTsutomu** [comment]
@rtonoue ありがとうございます。
反映しました。

https://pypi.org/project/ortoolpy/

https://github.com/SaitoTsutomu/ortoolpy/blob/1218c1f381df8a8ea5c19c63bddee51934d093b4/ortoolpy/etc.py#L1002-L1004

**Comment by rtonoue** [comment]
早速ありがとうございました！

**Comment by SaitoTsutomu** [comment]
反映済みなのでクローズ
